[project]
name = "algorithm-data-structure-graphviz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp==3.10.11",
    "attrs==19.3.0",
    "chardet==3.0.4",
    "graphviz==0.20.3",
]
